source 'https://rubygems.org'

gem 'octokit', '~> 2.0'
gem 'sinatra'
gem 'githubstats'
gem 'faraday-http-cache'
gem 'basiccache'
gem 'rake'
gem 'rubocop'
gem 'travis-lint'
gem 'coveralls'
gem 'rspec'
gem 'fuubar'
gem 'parser'
